### ISSUE TITLE
Cease and Desist

### ISSUE THREAD

**Issue by nickwalton** [Kornilov1/AI-Dungeon-2-Anons-modded-Versions-Colab#140]
Maintainers of this repo: Although the code for AI Dungeon 2 is open source the BYU PCCL logo (which you have co-opted into your own logo is owned by BYU) We don't approve of your usage of this logo in a work that promotes hate and anti-antisemitism. You are required to remove this from your website.

**Comment by thadunge2** [comment]
lol @nickwalton here's some choice excerpts from the data you trained your model on:

>“The fuckin’ Colonel? When he started getting sick that sonofabitch Harry started taking over more responsibility. Started doing shit HIS way, which was a lot more reactionary. I mean don’t get me wrong, I’m not some faggot peacenik, I’m all about creating a new strong society, like how America SHOULD’VE been, but fuck man. I’m not gonna kill children for no goddamn reason!”
>“Shut your fucking mouth and stop being a bitch! You’re all going to be wearing radiation suits anyway, which will keep your yellow ass safe. That alleviate your worries cupcake? Fuckin’ pussy ass faggot. You oughta be glad you’re even here in the first place. You don’t like the fuckin’ rules, you can fuckin’ leave and see how well you fare on your own. Now what’s it gonna be Nancy Boy?”
>“Significant other? What the fuck are we fucking faggots? Life partners and all that shit? Just say I’m your goddamn boyfriend. Shit, I’m practically your husband with as long as we’ve been together.”
>“That little faggot found out where Ben’s old shelter was and thought he was going to hide out from the current shitstorm in it with his boyfriend or whoever that other faggot he was with. Had to convince him that he had to go, he didn’t listen and tried to resist and well you saw how that turned out.”
>You end up getting expelled from school when you openly say that the Holocaust didn’t happen and that the Jew is using the black man as muscle to keep the white man down. Naturally your parents, as fucked up as they are, don’t approve of this sort of behavior and try to put you into therapy, but you call them race traitors and run away from home to your new skinhead buddies who embrace you with open arms where you have a great time with all of them.
>“That’s the biggest load of shit!” Lucy complains. “Everyone knows that any Jew in Dawnwood would be scared off by Carter Sr. and his white power bullshit.”
>“Meh, I think you’re about as accepted as anyone else around here. I mean I think the general assessment of you is that you’re a big tease that thinks she’s better than everyone else, but I mean its not like you’re a nigger or something.” Tina remarks.
>“Hell naw! Only niggers and spics have gangs! We’re an organization dedicated to the purity of the white race!”
>“Hey, your blood’s pure isn’t it? I mean you ain’t got some mud race mixed with you do ya? You ain’t no faggot are ya?”
>“As for Peter, that little faggot managed to find out where it was and thought he was going to hide out from the current shitstorm in it with his boyfriend or whoever that other faggot he was with. Had to convince him that he had to go, he didn’t listen and tried to resist and well you saw how that turned out.”
>And by the way, you were “virtually fucking” a fat forty year old pedophile, not some hot chick. Shit, 90% of the “chicks” online are really guys anyway. That’s another lesson you probably should’ve learned, you cyber fag.

kindly cease and desist yourself. also "anti-antisemitism" sends some mixed messages buddy

**Comment by VBPXKSMI** [comment]
Dear author, out of respect for the work that you did when creating this game, I, and the ones working on this repo, are taking down the aforementioned logo as per your request.

We only ask that you too address the issues with the data that you trained the model on, as it seems to cointain disrespectful words such as NIGGER/FAGGOT and many other racial or offensive slurs.

We (me and thousands more online) too are against anti-antisemitism, and hope that any and all JEWs in the world can live in peace and harmony, without fear of being persecuted or censored. 
We also hope that you will address this issue before the JIDF or BYU PCCL could take notice of it, because who knows what would happen otherwise.

Best regards, Anon.

**Comment by ShnitzelKiller** [comment]
There's no reason to be antagonistic, we just needed to change the logo, yes? Above comment aside, there is nothing in any of our forks that introduces additional bias towards these topics, given that they currently use the same model, which, as thadunge pointed out, has therefore seen the same data.

**Comment by machiavel23** [comment]
I also agree we made a small mistake keeping the picture, considering we're not even hosting any file of AIDungeon and only provide a frontend to run its modded versions. Really sorry, I was a bit in a rush when I did it. If you want, I can apologize by adding your repository to be playable in our frontend under the "Vanilla" appellation.

Something still bugs me however... You clearly say "**We** don't approve..."  and "You are **required**..." but first, I didn't see any legal document that could potentially "require" us something. Being nice and polite never hurted anyone you know. Well, except Jesus, maybe. Second, I went [there](https://copyright.byu.edu/about-us) and didn't see your name. I would be glad if you could provide an **evidence that you are actually a legal representative** of the BYU Copyright Licensing Office, because otherwise, it is called impersonation, and you could potentially go to jail for that. However, I'm pretty sure everything is fine and I'm just mistaking...

**Comment by deepbluesea** [comment]
I can't believe he said "anti-antisemitism" LOL
