### ISSUE TITLE
[W-FAQCT] Evaluation of the two other "top" AIDungeon repos

### ISSUE THREAD

**Issue by DonaldTsang** [Kornilov1/AI-Dungeon-2-Anons-modded-Versions-Colab#177]
**FAQ or Colab Troubleshooting?**

What about support for these two repos?
- https://github.com/nickwalton/AI-DungeonMaster (full auto)
- https://github.com/storybro/storybro (Reddit community edition)

**Add, delete or change?**

Add information regarding these two compared to Thadunge2 and Clover Edition

**Tell us what and why:**

The latter claims to have special features that the normal edition does not have.

**Comment by VBPXKSMI** [comment]
I'm not the one in charge of those pages but will throw my opinion anyway.

The first repo would be useless to add, as it is an older version of the base game (even older than the one most used before), and it isn't maintained nor useful anymore.

About the reddit repo: drama aside, their repo currently doesn't have much going on, and, from what I saw, its development slowed down considerably (it never was very active tbh, and now appears to be a 1 man team thing), so I'm not very sure about adding it. If it gets more complete, then it could be, but as it is right now I'm not very convinced.

Another thing to mention is that there are other reddit (more like discord) related repos and Colabs (these ones being derivatives of the Colab here), but excessively cluttering the Wiki with options isn't iddeal, it's quite bloated as it is. So we should take this also into account when adding things to avoid cluttering.

Other than this, I will let @SaberWonderland have the final say on the matter on these pages. 
What I'm sure about is that (unless you provide good arguments), I won't be adding these repos to the main "[Play!](https://github.com/VBPXKSMI/Open-CYOAI-Project/wiki/How-to-play)" page yet.

**Comment by DonaldTsang** [comment]
In that case what "new features" could you extract from these two repos in order to enhance Thadunge2 or Clover E? Might be e better idea to consolidate that way.

**Comment by VBPXKSMI** [comment]
First repo: nothing we can salvage here, as far as I can tell.

Reddit repo: despite claims of improvements to the base code, I have not seen such things (unless I'm blind), at least there are no improvements to the commands or main values. 
Even then, this falls under the tasks of the forks devs, not us directly, so it would be better asking them as the subject is the game itself.

No new models found here, so discard that aspect too.
Their Wiki is also very barebones too, despite addressing some things that our doesn't (mostly because those pages are in progress), so not much to look at there. 

At most, I think we could use some of the python tools that they used, but we would need to asses their utility and if they are even worth it in the first place.

Those are my thoughts, anyone is free to look into the issue directly, see what could be useful and share it.

**Comment by DonaldTsang** [comment]
Thank you for your analysis regarding the issue.

> At most, I think we could use some of the python tools that they used, but we would need to asses their utility and if they are even worth it in the first place.

**Comment by VBPXKSMI** [comment]
Np, will leave this issue open until @SaberWonderland says his opinion.

**Comment by SaberWonderland** [comment]
Not much to add really you already pointed out it's pointless to add them as they are. If the second one improves I might add it but as it is there's just no point. Also yeah our play page is bloated as it is. Gonna close this one out for now. You can resubmit if any major changes are made that you think means they deserve mentioning.
